
version: 2.1

orbs:
  maven: circleci/maven@1.4.1
workflows:
  build:
    jobs:
      - maven/test:
          executor: maven clean package
          steps:
            - checkout
            - mvn clean package