version: 2.1

orbs:
  maven: circleci/maven@1.3

executors:
  openjdk:
    docker:
      - image: circleci/openjdk:11.0.9-jdk-buster
      - image: cpr-frontend
      - image: cpr-login
      - image: cpr-course-manager
      - image: cpr-course-viewer
      - image: cpr-peer-review-teams
      - image: cpr-professor-assignment
      - image: cpr-student-assignment
      - image: cpr-student-peer-review-assignment
      - image: mongo:5.0.6
        command: mongod --port ${MONGO_PORT}
      - image: mongo:5.0.6
        command: mongod --port ${MONGO2_PORT}
      - image: mongo:5.0.6
        command: mongod --port ${MONGO3_PORT}
      - image: mongo:5.0.6
        command: mongod --port ${MONGO4_PORT}
      - image: mongo:5.0.6
        command: mongod --port ${MONGO5_PORT}

workflows:
  verify: # workflow name
    jobs:
      - maven/test:
          executor: openjdk
          steps:
            - checkout
            - run: mvn test
