
version: 2.1

orbs:
  maven: circleci/maven@1.4.1

jobs:
    maven-compile:
        executor: maven/default
    steps:
      - checkout
      - run:
          name: clean
          command: mvn clean

      - run:
            name: compile
            command: mvn package


workflows:
  build:
    jobs:
      - maven-compile

