
version: 2.1

orbs:
  maven: circleci/maven@1.4.0

jobs:
  build:
    docker:
      - image: cimg/base:stable
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD

    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - docker-compose -f "docker-compose-local.yml" up -d --build

workflows:
  build:
    jobs:
      - build
