
version: 2.1

orbs:
  maven: circleci/maven@1.4.1

jobs:
  clean:
    executor: maven/default
    steps:
      - checkout
      - run: mvn clean

  build:
    executor: maven/default
    steps:
      - checkout
      - run: mvn package

workflows:
  clean_and_build:
    jobs:
      - clean
      - build:
          requires:
            - clean