
version: 2.1

orbs:
  maven: circleci/maven@1.4.1

jobs:
    maven compile:
        executor: maven/default
    steps:
      - checkout
      - command:
        - mvn clean
        - mvn package



workflows:
  build:
    jobs:
      - maven compile

