
version: 2.1

orbs:
  maven: circleci/maven@1.4.1

jobs:
  clean_course_manager:
    parameters:
      app_src_directory:
        type: string
        default: "/backend/course-manager-microservice"
    executor: maven/default
    steps:
      - checkout
      - run: mvn dir/backend/course-manager-microservice clean

  build_course_manager:
    parameters:
      app_src_directory:
        type: string
        default: "/backend/course-manager-microservice"
    executor: maven/default
    steps:
      - checkout
      - run: mvn dir/backend/course-manager-microservice package

workflows:
  clean_and_build:
    jobs:
      - clean_course_manager
      - build_course_manager:
          requires:
            - clean_course_manager